### PR TITLE
Added new color theme to website

### PR DESCRIPTION
**Pull request by honey7100**
image
image
image
image

### CODE REVIEW

**Comment by BryanTriana** [comment]
Can you also show how the item submission dialog looks like?

**Comment by honey7100** [comment]
> Can you also show how the item submission dialog looks like?

image

**Comment by BryanTriana** [comment]
Can you also post screenshot with the item being searched?

**Comment by honey7100** [comment]
image

**Comment by BryanTriana** [comment]
Yeah the aspect ratio looks different to how it looked before. Can you modify the item-image style in style.css so that the width of the image doesn't look weird?

**Comment by honey7100** [comment]
Fixed! 
image
image

**Comment by honey7100** [comment]
Changed the colors to match the Blockbuster colors more
image

**Comment by honey7100** [comment]
> .card-img,.card-img-top,.card-img-bottom{flex-shrink:0}

image

**Comment by honey7100** [comment]
Which one looks better? @rharagutchi @BryanTriana 
image
OR
image

**Comment by BryanTriana** [comment]
second one

**Comment by codewithjess** [comment]
> second one

The 2nd one looks too narrow??

**Comment by rharagutchi** [comment]
it is, I was just going to debug the css after it got deployed :)

**Pull request merged**
